export enum GLOBAL_ERRORS {
	INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
	MISSING_AUTH_TOKEN = "MISSING_AUTH_TOKEN",

	ACCESS_TOKEN_EXPIRED = "ACCESS_TOKEN_EXPIRED",
	ACCESS_TOKEN_INVALID = "ACCESS_TOKEN_INVALID",

	REFRESH_TOKEN_EXPIRED = "REFRESH_TOKEN_EXPIRED",
	REFRESH_TOKEN_INVALID = "REFRESH_TOKEN_INVALID",

	USER_NOT_FOUND = "USER_NOT_FOUND",
	USER_INPUT_INVALID = "USER_INPUT_INVALID",
	USER_ROLE_INVALID = "USER_ROLE_INVALID",
	NOT_ENOUGH_PERMISSIONS = "NOT_ENOUGH_PERMISSIONS",
	INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
	INSTANCE_ALREADY_INITIALIZED = "INSTANCE_ALREADY_INITIALIZED",

	NOT_FOUND = "NOT_FOUND",
}
